** NUMPY ASSISMENT **

In [54]:
import numpy as np

Simple codes = 

In [55]:
#Simplest way to create an array in Numpy is to use Python List
a = [1,2,4,3]
print(a)

[1, 2, 4, 3]


In [56]:
#List to array
b=np.array(a)
b

array([1, 2, 4, 3])

In [57]:
#list to array
c=np.array([1,2,3,4])
c

array([1, 2, 3, 4])

In [58]:
#adding number to the list given
d=b+10
d

array([11, 12, 14, 13])

In [59]:
#shape is used to get the rows and column in the string and dtype is used to get  the datatype of the input 
a=np.array([1,2,3,4,5,6])
print(a.shape)
print(a.dtype)


(6,)
int32


In [60]:
#Float numbers 
b  = np.array([9.0,2.8,5.6,7.9])
print(b.dtype)

float64


In [61]:
d = np.array([
    [[1, 2,3],
    [4, 5, 6]],
    [[7, 8,9],
    [10, 11, 12]]
])
print(d.shape)
print(d)

(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [62]:
#Making a zero metrix 
#(2,2)is 2 rows and columns and the dtype is the data type , which is not necessory ..
import numpy as np
x=np.zeros((4,4), dtype=np.int16)
print(x)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [63]:
import numpy as np
y=np.ones((1,2,3), dtype=np.int16)
print(y.shape)	
print(y)

(1, 2, 3)
[[[1 1 1]
  [1 1 1]]]


In [64]:
#Reshaping the metrix of 2,3 to 3,2 .
import numpy as np
e  = np.array([(9,8,5), (4,3,6)])
print(e)
e.reshape(3,2)

[[9 8 5]
 [4 3 6]]


array([[9, 8],
       [5, 4],
       [3, 6]])

In [65]:
#Flatten the metrix .
e  = np.array([(9,8,5), (4,3,6)])
print(e)
e.flatten()

[[9 8 5]
 [4 3 6]]


array([9, 8, 5, 4, 3, 6])

In [66]:
## Horitzontal Stack
import numpy as np
a= np.array([4,5,6])
b= np.array([1,7,4])
print('Horizontal Append:', np.hstack((a,b)))

Horizontal Append: [4 5 6 1 7 4]


In [67]:
## Vertical Stack
import numpy as np
a= np.array([4,5,6])
b= np.array([1,7,4])
print('Vertical Append:', np.vstack((a,b)))

Vertical Append: [[4 5 6]
 [1 7 4]]


In [68]:
#To generate random numbers for Gaussian distribution use
#numpy.random.normal(loc, scale, size)
#Loc: the mean. The center of distribution
#scale: standard deviation.
#Size: number of returns
normal_array = np.random.normal(10, 1, 25)
print(normal_array)	

[ 8.91927398  9.99122985  9.51167986  9.61611184  9.90690917 11.02243157
 10.52088279  9.65239641 10.03895968 10.40228625  9.06462415 10.21511346
  8.35543581  9.1977735   9.22002431 10.05719978  8.78555878  8.6473875
  8.13216912  9.3741472   8.76388175 10.93326269 10.4312768   9.9795162
  9.65436846]


In [69]:
#ALL 1 array .
import numpy as np 
a=np.array(np.ones((3,3)))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [70]:
# Asarray
# The asarray()function is used when you want to convert an input to an array. The input could be a lists, tuple, ndarray, etc.
# Syntax:
# numpy.asarray(data, dtype=None, order=None)[source]
# Here,
# data: Data that you want to convert to an array
# dtype: This is an optional argument. If not specified, the data type is inferred from the input data
# Order: Default is C which is an essential row style. Other option is F (Fortan-style)

np.asarray(a)[2]=2
print(a)


[[1. 1. 1.]
 [1. 1. 1.]
 [2. 2. 2.]]


In [71]:
#numpy.arange() is an inbuilt numpy function that returns an ndarray object containing evenly spaced values within a defined interval. For instance, you want to create values from 1 to 10; you can use numpy.arange() function.
#Syntax:
#numpy.arange(start, stop,step) 
#Start: Start of interval
#Stop: End of interval
#Step: Spacing between values. Default step is 1

a=np.arange(0,200,2)
a

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198])

In [72]:
# Linspace
# numpy.linspace(start, stop, num, endpoint)
# Here,
# Start: Starting value of the sequence
# Stop: End value of the sequence
# Num: Number of samples to generate. Default is 50
# Endpoint: If True (default), stop is the last value. If False, stop value is not included.

a=np.linspace(0,200,100,True)
b=np.linspace(0,200,100,False)
print(a)
print(b)



[  0.           2.02020202   4.04040404   6.06060606   8.08080808
  10.1010101   12.12121212  14.14141414  16.16161616  18.18181818
  20.2020202   22.22222222  24.24242424  26.26262626  28.28282828
  30.3030303   32.32323232  34.34343434  36.36363636  38.38383838
  40.4040404   42.42424242  44.44444444  46.46464646  48.48484848
  50.50505051  52.52525253  54.54545455  56.56565657  58.58585859
  60.60606061  62.62626263  64.64646465  66.66666667  68.68686869
  70.70707071  72.72727273  74.74747475  76.76767677  78.78787879
  80.80808081  82.82828283  84.84848485  86.86868687  88.88888889
  90.90909091  92.92929293  94.94949495  96.96969697  98.98989899
 101.01010101 103.03030303 105.05050505 107.07070707 109.09090909
 111.11111111 113.13131313 115.15151515 117.17171717 119.19191919
 121.21212121 123.23232323 125.25252525 127.27272727 129.29292929
 131.31313131 133.33333333 135.35353535 137.37373737 139.39393939
 141.41414141 143.43434343 145.45454545 147.47474747 149.49494949
 151.51515

In [73]:
# Logspace
# numpy.logspace(start, stop, num, endpoint)

a=np.logspace(1,10,1,False)
a

array([10.])

In [74]:
# Item Size
import numpy as np 
x = np.array([(1,2,3), (4,5,6)] )
a=x.itemsize	
y = np.array([(1,2,3), (4,5,6)], dtype=np.complex64)
b=y.itemsize
z = np.array([(1,2,3), (4,5,6)] , dtype=np.complex128)
e=z.itemsize
print(a)
print(b)
print(e)	

4
8
16


In [75]:
# slicing 
c=x[0]
print(c)
d=x[1]
print(d)

[1 2 3]
[4 5 6]


In [76]:
print('Second column:', x[1,1])	

Second column: 5


In [77]:
# Min , Max Mean , Median , Std 
a=np.random.normal(0,1,5)
print(a)
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))

[-0.7256904  -0.04479605  0.71623878 -0.14848867  1.08802332]
-0.7256903979574091
1.0880233221100881
0.17705739611449894
-0.044796050457838285
0.646641825423712


In [78]:
# Dot product.
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.dot(a,b)
print(c)

32


In [79]:
# Matmul
a=[[1,2],[4,6]]
b=[[1,2],[4,6]]
print(a)
print(b)
c=np.matmul ( a , b )
print(c)



[[1, 2], [4, 6]]
[[1, 2], [4, 6]]
[[ 9 14]
 [28 44]]


In [80]:
# Inverse of the array
a=[[1,2],[4,6]]
b=np.linalg.inv(a)
print(b)

[[-3.   1. ]
 [ 2.  -0.5]]


In [81]:
# Determinat of the metrix

a=[[1,2],[4,6]]
b=np.linalg.det(a)
print(b)

-2.0


In [82]:
#Matric rank

a=[[1,2],[4,6]]
b=np.linalg.matrix_rank(a)
b

2

In [83]:
#Matric power

a=[[1,2],[4,6]]
b=np.linalg.matrix_power(a,7)
b

array([[182113, 285686],
       [571372, 896328]])

In [84]:
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.linalg.eig(a)
c=np.linalg.eigh(a)
d=np.linalg.eigvals(a)
e=np.linalg.eigvalsh(a)
print(b)
print(c)
print(d)
print(e)

(array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16]), array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))
(array([-3.15746784, -0.67276795, 18.8302358 ]), array([[-0.80238891,  0.43402538, -0.40962667],
       [-0.16812656, -0.82296167, -0.54264865],
       [ 0.57263033,  0.36654613, -0.73330651]]))
[ 1.61168440e+01 -1.11684397e+00 -9.75918483e-16]
[-3.15746784 -0.67276795 18.8302358 ]


In [85]:
# diagonal metrix
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.diagonal(a)
b

array([1, 5, 9])

In [86]:
# Transpose of a metrix
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.transpose(a)
b

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [87]:
# Trace of a metrix
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.trace(a)
b

15